// <auto-generated />
namespace LungmenSoftware.MigrationForChangeRequestData
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeunnecessaryCols : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeunnecessaryCols));
        
        string IMigrationMetadata.Id
        {
            get { return "201610190849001_removeunnecessaryCols"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
