//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LungmenSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeRequestProcessLog
    {
        public System.Guid ChangeLogId { get; set; }
        public string ChangeRequestId { get; set; }
        public string StatusDate { get; set; }
    }
}
