//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LungmenSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeRequest
    {
        public ChangeRequest()
        {
            this.ImpDocs = new HashSet<ImpDoc>();
        }
    
        public System.Guid ChangeRequestId { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<System.DateTime> InitialDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifier { get; set; }
        public string Reviewer { get; set; }
        public string Initiator { get; set; }
        public Nullable<int> ChangeStatusId { get; set; }
        public string RequestNo { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsFailed { get; set; }
        public Nullable<System.DateTime> StatusProcessDate { get; set; }
        public Nullable<int> ChangeRequestTypeId { get; set; }
    
        public virtual ChangeStatu ChangeStatu { get; set; }
        public virtual ICollection<ImpDoc> ImpDocs { get; set; }
        public virtual ChangeRequestType ChangeRequestType { get; set; }
    }
}
