//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LungmenSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoxSoftware
    {
       
    
        public int FoxSoftwareId { get; set; }
        public string SoftwareName { get; set; }
        public string Software_Library_Identification { get; set; }
        public string Media_Identification { get; set; }
        public string Procedure { get; set; }
        public Nullable<int> FoxSoftware_WorkstationTypeId { get; set; }
        public Nullable<int> FoxSoftwareTypeId { get; set; }
    
        public virtual FoxSoftwareType FoxSoftwareType { get; set; }
        public virtual ICollection<WKAndFoxJoinTable> WKAndFoxJoinTables { get; set; }
    }
}
