//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LungmenSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoxWorkStation
    {
    
        public int WorkStationId { get; set; }
        public string WorkStationName { get; set; }
        public string Owner { get; set; }
        public Nullable<int> WorkStationHardwareTypeId { get; set; }
        public Nullable<int> WorkStationSoftwareTypeId { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual ICollection<WKAndFoxJoinTable> WKAndFoxJoinTables { get; set; }
        public virtual WorkStationHardwareType WorkStationHardwareType { get; set; }
    }
}
