//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LungmenSoftware.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LungmenSoftwareDataEntities : DbContext
    {
        public LungmenSoftwareDataEntities()
            : base("name=LungmenSoftwareDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FoxSoftware> FoxSoftwares { get; set; }
        public virtual DbSet<FoxSoftwareType> FoxSoftwareTypes { get; set; }
        public virtual DbSet<FoxWorkStation> FoxWorkStations { get; set; }
        public virtual DbSet<HistorialChangeRecord> HistorialChangeRecords { get; set; }
        public virtual DbSet<WKAndFoxJoinTable> WKAndFoxJoinTables { get; set; }
        public virtual DbSet<WorkStationHardwareType> WorkStationHardwareTypes { get; set; }
        public virtual DbSet<WorkStationSoftwareType> WorkStationSoftwareTypes { get; set; }
    }
}
